protocol: kcp
host: 0.0.0.0
port: 3001
read-buffer-size: 1024
write-buffer-size: 1024
time-tolerance: 300 # seconds
registry-max-bucket-num: 64
nsqd-address: ["localhost:4150"]
nsqlookupd-address: "localhost:4161"
receiver-num: 10
sender-num: 10
processor-num: 3
node-id: 0
endpoint: http://101.37.76.38:8084
instance: x02caat39505
ak-id: abcdef
ak-secret: abcdef