// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectStatus int32

const (
	ConnectStatus_CONNECT_STATUS_UNSPECIFIED ConnectStatus = 0
	ConnectStatus_SUCCESS                    ConnectStatus = 1
	ConnectStatus_ALREADY_EXIST              ConnectStatus = 2
	ConnectStatus_FAIL                       ConnectStatus = 3
)

// Enum value maps for ConnectStatus.
var (
	ConnectStatus_name = map[int32]string{
		0: "CONNECT_STATUS_UNSPECIFIED",
		1: "SUCCESS",
		2: "ALREADY_EXIST",
		3: "FAIL",
	}
	ConnectStatus_value = map[string]int32{
		"CONNECT_STATUS_UNSPECIFIED": 0,
		"SUCCESS":                    1,
		"ALREADY_EXIST":              2,
		"FAIL":                       3,
	}
)

func (x ConnectStatus) Enum() *ConnectStatus {
	p := new(ConnectStatus)
	*p = x
	return p
}

func (x ConnectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (ConnectStatus) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x ConnectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectStatus.Descriptor instead.
func (ConnectStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

// 从 Go 的 MessageUnitType 常量迁移来的枚举
type MessageUnitType int32

const (
	MessageUnitType_MESSAGE_UNIT_TYPE_UNSPECIFIED MessageUnitType = 0 // proto3 要求第一个值为 0
	MessageUnitType_TEXT                          MessageUnitType = 1
	MessageUnitType_CALL                          MessageUnitType = 2
	MessageUnitType_ANSWER                        MessageUnitType = 3
	MessageUnitType_ESTABLISH                     MessageUnitType = 4
)

// Enum value maps for MessageUnitType.
var (
	MessageUnitType_name = map[int32]string{
		0: "MESSAGE_UNIT_TYPE_UNSPECIFIED",
		1: "TEXT",
		2: "CALL",
		3: "ANSWER",
		4: "ESTABLISH",
	}
	MessageUnitType_value = map[string]int32{
		"MESSAGE_UNIT_TYPE_UNSPECIFIED": 0,
		"TEXT":                          1,
		"CALL":                          2,
		"ANSWER":                        3,
		"ESTABLISH":                     4,
	}
)

func (x MessageUnitType) Enum() *MessageUnitType {
	p := new(MessageUnitType)
	*p = x
	return p
}

func (x MessageUnitType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageUnitType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (MessageUnitType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x MessageUnitType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageUnitType.Descriptor instead.
func (MessageUnitType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MessageType type = 1;
	CreatedTime int64 `protobuf:"varint,2,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*Message_ConnectMessageRequest
	//	*Message_ConnectMessageResponse
	//	*Message_CandidateMessage
	//	*Message_ChatMessage
	Data          isMessage_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *Message) GetData() isMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetConnectMessageRequest() *ConnectMessageRequest {
	if x != nil {
		if x, ok := x.Data.(*Message_ConnectMessageRequest); ok {
			return x.ConnectMessageRequest
		}
	}
	return nil
}

func (x *Message) GetConnectMessageResponse() *ConnectMessageResponse {
	if x != nil {
		if x, ok := x.Data.(*Message_ConnectMessageResponse); ok {
			return x.ConnectMessageResponse
		}
	}
	return nil
}

func (x *Message) GetCandidateMessage() *CandidateMessage {
	if x != nil {
		if x, ok := x.Data.(*Message_CandidateMessage); ok {
			return x.CandidateMessage
		}
	}
	return nil
}

func (x *Message) GetChatMessage() *ChatMessage {
	if x != nil {
		if x, ok := x.Data.(*Message_ChatMessage); ok {
			return x.ChatMessage
		}
	}
	return nil
}

type isMessage_Data interface {
	isMessage_Data()
}

type Message_ConnectMessageRequest struct {
	ConnectMessageRequest *ConnectMessageRequest `protobuf:"bytes,3,opt,name=connect_message_request,json=connectMessageRequest,proto3,oneof"`
}

type Message_ConnectMessageResponse struct {
	ConnectMessageResponse *ConnectMessageResponse `protobuf:"bytes,4,opt,name=connect_message_response,json=connectMessageResponse,proto3,oneof"`
}

type Message_CandidateMessage struct {
	CandidateMessage *CandidateMessage `protobuf:"bytes,5,opt,name=candidate_message,json=candidateMessage,proto3,oneof"`
}

type Message_ChatMessage struct {
	ChatMessage *ChatMessage `protobuf:"bytes,6,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

func (*Message_ConnectMessageRequest) isMessage_Data() {}

func (*Message_ConnectMessageResponse) isMessage_Data() {}

func (*Message_CandidateMessage) isMessage_Data() {}

func (*Message_ChatMessage) isMessage_Data() {}

// 已有的消息与枚举
type ConnectMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectMessageRequest) Reset() {
	*x = ConnectMessageRequest{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectMessageRequest) ProtoMessage() {}

func (x *ConnectMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectMessageRequest.ProtoReflect.Descriptor instead.
func (*ConnectMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConnectMessageRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type ConnectMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ConnectStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=message.ConnectStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectMessageResponse) Reset() {
	*x = ConnectMessageResponse{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectMessageResponse) ProtoMessage() {}

func (x *ConnectMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectMessageResponse.ProtoReflect.Descriptor instead.
func (*ConnectMessageResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectMessageResponse) GetStatus() ConnectStatus {
	if x != nil {
		return x.Status
	}
	return ConnectStatus_CONNECT_STATUS_UNSPECIFIED
}

type CandidateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteId      string                 `protobuf:"bytes,1,opt,name=remote_id,json=remoteId,proto3" json:"remote_id,omitempty"`
	SdpMid        string                 `protobuf:"bytes,2,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMlineIndex int32                  `protobuf:"varint,3,opt,name=sdp_mline_index,json=sdpMlineIndex,proto3" json:"sdp_mline_index,omitempty"`
	Sdp           string                 `protobuf:"bytes,4,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateMessage) Reset() {
	*x = CandidateMessage{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateMessage) ProtoMessage() {}

func (x *CandidateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateMessage.ProtoReflect.Descriptor instead.
func (*CandidateMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *CandidateMessage) GetRemoteId() string {
	if x != nil {
		return x.RemoteId
	}
	return ""
}

func (x *CandidateMessage) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *CandidateMessage) GetSdpMlineIndex() int32 {
	if x != nil {
		return x.SdpMlineIndex
	}
	return 0
}

func (x *CandidateMessage) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

// 从 ChatMessage 迁移
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteId      string                 `protobuf:"bytes,1,opt,name=remote_id,json=remoteId,proto3" json:"remote_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	MessageChain  []*MessageUnit         `protobuf:"bytes,3,rep,name=message_chain,json=messageChain,proto3" json:"message_chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *ChatMessage) GetRemoteId() string {
	if x != nil {
		return x.RemoteId
	}
	return ""
}

func (x *ChatMessage) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ChatMessage) GetMessageChain() []*MessageUnit {
	if x != nil {
		return x.MessageChain
	}
	return nil
}

// 从 MessageUnit 迁移
type MessageUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageUnitType        `protobuf:"varint,1,opt,name=type,proto3,enum=message.MessageUnitType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageUnit) Reset() {
	*x = MessageUnit{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUnit) ProtoMessage() {}

func (x *MessageUnit) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUnit.ProtoReflect.Descriptor instead.
func (*MessageUnit) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *MessageUnit) GetType() MessageUnitType {
	if x != nil {
		return x.Type
	}
	return MessageUnitType_MESSAGE_UNIT_TYPE_UNSPECIFIED
}

func (x *MessageUnit) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\amessage\"\xf0\x02\n" +
	"\aMessage\x12!\n" +
	"\fcreated_time\x18\x02 \x01(\x03R\vcreatedTime\x12X\n" +
	"\x17connect_message_request\x18\x03 \x01(\v2\x1e.message.ConnectMessageRequestH\x00R\x15connectMessageRequest\x12[\n" +
	"\x18connect_message_response\x18\x04 \x01(\v2\x1f.message.ConnectMessageResponseH\x00R\x16connectMessageResponse\x12H\n" +
	"\x11candidate_message\x18\x05 \x01(\v2\x19.message.CandidateMessageH\x00R\x10candidateMessage\x129\n" +
	"\fchat_message\x18\x06 \x01(\v2\x14.message.ChatMessageH\x00R\vchatMessageB\x06\n" +
	"\x04data\"J\n" +
	"\x15ConnectMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"H\n" +
	"\x16ConnectMessageResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.message.ConnectStatusR\x06status\"\x82\x01\n" +
	"\x10CandidateMessage\x12\x1b\n" +
	"\tremote_id\x18\x01 \x01(\tR\bremoteId\x12\x17\n" +
	"\asdp_mid\x18\x02 \x01(\tR\x06sdpMid\x12&\n" +
	"\x0fsdp_mline_index\x18\x03 \x01(\x05R\rsdpMlineIndex\x12\x10\n" +
	"\x03sdp\x18\x04 \x01(\tR\x03sdp\"\x88\x01\n" +
	"\vChatMessage\x12\x1b\n" +
	"\tremote_id\x18\x01 \x01(\tR\bremoteId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x129\n" +
	"\rmessage_chain\x18\x03 \x03(\v2\x14.message.MessageUnitR\fmessageChain\"U\n" +
	"\vMessageUnit\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.message.MessageUnitTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*Y\n" +
	"\rConnectStatus\x12\x1e\n" +
	"\x1aCONNECT_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\x11\n" +
	"\rALREADY_EXIST\x10\x02\x12\b\n" +
	"\x04FAIL\x10\x03*c\n" +
	"\x0fMessageUnitType\x12!\n" +
	"\x1dMESSAGE_UNIT_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01\x12\b\n" +
	"\x04CALL\x10\x02\x12\n" +
	"\n" +
	"\x06ANSWER\x10\x03\x12\r\n" +
	"\tESTABLISH\x10\x04B\rZ\vdto/messageb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_message_proto_goTypes = []any{
	(ConnectStatus)(0),             // 0: message.ConnectStatus
	(MessageUnitType)(0),           // 1: message.MessageUnitType
	(*Message)(nil),                // 2: message.Message
	(*ConnectMessageRequest)(nil),  // 3: message.ConnectMessageRequest
	(*ConnectMessageResponse)(nil), // 4: message.ConnectMessageResponse
	(*CandidateMessage)(nil),       // 5: message.CandidateMessage
	(*ChatMessage)(nil),            // 6: message.ChatMessage
	(*MessageUnit)(nil),            // 7: message.MessageUnit
}
var file_message_proto_depIdxs = []int32{
	3, // 0: message.Message.connect_message_request:type_name -> message.ConnectMessageRequest
	4, // 1: message.Message.connect_message_response:type_name -> message.ConnectMessageResponse
	5, // 2: message.Message.candidate_message:type_name -> message.CandidateMessage
	6, // 3: message.Message.chat_message:type_name -> message.ChatMessage
	0, // 4: message.ConnectMessageResponse.status:type_name -> message.ConnectStatus
	7, // 5: message.ChatMessage.message_chain:type_name -> message.MessageUnit
	1, // 6: message.MessageUnit.type:type_name -> message.MessageUnitType
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_message_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_ConnectMessageRequest)(nil),
		(*Message_ConnectMessageResponse)(nil),
		(*Message_CandidateMessage)(nil),
		(*Message_ChatMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
