// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: message.proto

package datas

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_CONNECT                  MessageType = 1
	MessageType_CHAT                     MessageType = 2
	MessageType_CANDIDATE                MessageType = 3
	MessageType_FETCH                    MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "CONNECT",
		2: "CHAT",
		3: "CANDIDATE",
		4: "FETCH",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"CONNECT":                  1,
		"CHAT":                     2,
		"CANDIDATE":                3,
		"FETCH":                    4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type AckStatus int32

const (
	AckStatus_ACK_STATUS_UNSPECIFIED AckStatus = 0
	AckStatus_SENDING                AckStatus = 4
	AckStatus_SENT                   AckStatus = 5
	AckStatus_FAIL                   AckStatus = 3
)

// Enum value maps for AckStatus.
var (
	AckStatus_name = map[int32]string{
		0: "ACK_STATUS_UNSPECIFIED",
		4: "SENDING",
		5: "SENT",
		3: "FAIL",
	}
	AckStatus_value = map[string]int32{
		"ACK_STATUS_UNSPECIFIED": 0,
		"SENDING":                4,
		"SENT":                   5,
		"FAIL":                   3,
	}
)

func (x AckStatus) Enum() *AckStatus {
	p := new(AckStatus)
	*p = x
	return p
}

func (x AckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (AckStatus) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x AckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckStatus.Descriptor instead.
func (AckStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

// 从 Go 的 MessageUnitType 常量迁移来的枚举
type MessageUnitType int32

const (
	MessageUnitType_MESSAGE_UNIT_TYPE_UNSPECIFIED MessageUnitType = 0 // proto3 要求第一个值为 0
	MessageUnitType_TEXT                          MessageUnitType = 1
	MessageUnitType_CALL                          MessageUnitType = 2
	MessageUnitType_ANSWER                        MessageUnitType = 3
	MessageUnitType_ESTABLISH                     MessageUnitType = 4
)

// Enum value maps for MessageUnitType.
var (
	MessageUnitType_name = map[int32]string{
		0: "MESSAGE_UNIT_TYPE_UNSPECIFIED",
		1: "TEXT",
		2: "CALL",
		3: "ANSWER",
		4: "ESTABLISH",
	}
	MessageUnitType_value = map[string]int32{
		"MESSAGE_UNIT_TYPE_UNSPECIFIED": 0,
		"TEXT":                          1,
		"CALL":                          2,
		"ANSWER":                        3,
		"ESTABLISH":                     4,
	}
)

func (x MessageUnitType) Enum() *MessageUnitType {
	p := new(MessageUnitType)
	*p = x
	return p
}

func (x MessageUnitType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageUnitType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[2].Descriptor()
}

func (MessageUnitType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[2]
}

func (x MessageUnitType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageUnitType.Descriptor instead.
func (MessageUnitType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

// TODO 不知道是否合理，到时候再改吧
type Message struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Type        MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=message.MessageType" json:"type,omitempty"`
	SenderId    string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId  string                 `protobuf:"bytes,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	CreatedTime int64                  `protobuf:"varint,4,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	MessageId   string                 `protobuf:"bytes,11,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConnId      int64                  `protobuf:"varint,12,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*Message_Ack
	//	*Message_Candidate
	//	*Message_Chat
	//	*Message_Call
	//	*Message_Answer
	Data          isMessage_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *Message) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetConnId() int64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *Message) GetData() isMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Data.(*Message_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Message) GetCandidate() *Candidate {
	if x != nil {
		if x, ok := x.Data.(*Message_Candidate); ok {
			return x.Candidate
		}
	}
	return nil
}

func (x *Message) GetChat() *Chat {
	if x != nil {
		if x, ok := x.Data.(*Message_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Message) GetCall() *Sdp {
	if x != nil {
		if x, ok := x.Data.(*Message_Call); ok {
			return x.Call
		}
	}
	return nil
}

func (x *Message) GetAnswer() *Sdp {
	if x != nil {
		if x, ok := x.Data.(*Message_Answer); ok {
			return x.Answer
		}
	}
	return nil
}

type isMessage_Data interface {
	isMessage_Data()
}

type Message_Ack struct {
	Ack *Ack `protobuf:"bytes,6,opt,name=ack,proto3,oneof"`
}

type Message_Candidate struct {
	// Connect   connect   = 5;
	Candidate *Candidate `protobuf:"bytes,7,opt,name=candidate,proto3,oneof"`
}

type Message_Chat struct {
	Chat *Chat `protobuf:"bytes,8,opt,name=chat,proto3,oneof"`
}

type Message_Call struct {
	Call *Sdp `protobuf:"bytes,9,opt,name=call,proto3,oneof"`
}

type Message_Answer struct {
	Answer *Sdp `protobuf:"bytes,10,opt,name=answer,proto3,oneof"`
}

func (*Message_Ack) isMessage_Data() {}

func (*Message_Candidate) isMessage_Data() {}

func (*Message_Chat) isMessage_Data() {}

func (*Message_Call) isMessage_Data() {}

func (*Message_Answer) isMessage_Data() {}

type Sdp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sdp           string                 `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sdp) Reset() {
	*x = Sdp{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sdp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sdp) ProtoMessage() {}

func (x *Sdp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sdp.ProtoReflect.Descriptor instead.
func (*Sdp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *Sdp) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

// 已有的消息与枚举
type Connect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connect) Reset() {
	*x = Connect{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connect) ProtoMessage() {}

func (x *Connect) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connect.ProtoReflect.Descriptor instead.
func (*Connect) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *Connect) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        AckStatus              `protobuf:"varint,1,opt,name=status,proto3,enum=message.AckStatus" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetStatus() AckStatus {
	if x != nil {
		return x.Status
	}
	return AckStatus_ACK_STATUS_UNSPECIFIED
}

func (x *Ack) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Ack) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SdpMid        string                 `protobuf:"bytes,2,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMlineIndex int32                  `protobuf:"varint,3,opt,name=sdp_mline_index,json=sdpMlineIndex,proto3" json:"sdp_mline_index,omitempty"`
	Sdp           string                 `protobuf:"bytes,4,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *Candidate) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *Candidate) GetSdpMlineIndex() int32 {
	if x != nil {
		return x.SdpMlineIndex
	}
	return 0
}

func (x *Candidate) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

// 从 ChatMessage 迁移
type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	MessageChain  []*MessageUnit         `protobuf:"bytes,3,rep,name=message_chain,json=messageChain,proto3" json:"message_chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *Chat) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Chat) GetMessageChain() []*MessageUnit {
	if x != nil {
		return x.MessageChain
	}
	return nil
}

// 从 MessageUnit 迁移
type MessageUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageUnitType        `protobuf:"varint,1,opt,name=type,proto3,enum=message.MessageUnitType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageUnit) Reset() {
	*x = MessageUnit{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUnit) ProtoMessage() {}

func (x *MessageUnit) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUnit.ProtoReflect.Descriptor instead.
func (*MessageUnit) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *MessageUnit) GetType() MessageUnitType {
	if x != nil {
		return x.Type
	}
	return MessageUnitType_MESSAGE_UNIT_TYPE_UNSPECIFIED
}

func (x *MessageUnit) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\amessage\"\x9b\x03\n" +
	"\aMessage\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.message.MessageTypeR\x04type\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x03 \x01(\tR\n" +
	"receiverId\x12!\n" +
	"\fcreated_time\x18\x04 \x01(\x03R\vcreatedTime\x12\x1d\n" +
	"\n" +
	"message_id\x18\v \x01(\tR\tmessageId\x12\x17\n" +
	"\aconn_id\x18\f \x01(\x03R\x06connId\x12 \n" +
	"\x03ack\x18\x06 \x01(\v2\f.message.AckH\x00R\x03ack\x122\n" +
	"\tcandidate\x18\a \x01(\v2\x12.message.CandidateH\x00R\tcandidate\x12#\n" +
	"\x04chat\x18\b \x01(\v2\r.message.ChatH\x00R\x04chat\x12\"\n" +
	"\x04call\x18\t \x01(\v2\f.message.SdpH\x00R\x04call\x12&\n" +
	"\x06answer\x18\n" +
	" \x01(\v2\f.message.SdpH\x00R\x06answerB\x06\n" +
	"\x04data\"\x17\n" +
	"\x03Sdp\x12\x10\n" +
	"\x03sdp\x18\x02 \x01(\tR\x03sdp\",\n" +
	"\aConnect\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\"h\n" +
	"\x03Ack\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.message.AckStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"^\n" +
	"\tCandidate\x12\x17\n" +
	"\asdp_mid\x18\x02 \x01(\tR\x06sdpMid\x12&\n" +
	"\x0fsdp_mline_index\x18\x03 \x01(\x05R\rsdpMlineIndex\x12\x10\n" +
	"\x03sdp\x18\x04 \x01(\tR\x03sdp\"d\n" +
	"\x04Chat\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x129\n" +
	"\rmessage_chain\x18\x03 \x03(\v2\x14.message.MessageUnitR\fmessageChain\"U\n" +
	"\vMessageUnit\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.message.MessageUnitTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\\\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCONNECT\x10\x01\x12\b\n" +
	"\x04CHAT\x10\x02\x12\r\n" +
	"\tCANDIDATE\x10\x03\x12\t\n" +
	"\x05FETCH\x10\x04*H\n" +
	"\tAckStatus\x12\x1a\n" +
	"\x16ACK_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSENDING\x10\x04\x12\b\n" +
	"\x04SENT\x10\x05\x12\b\n" +
	"\x04FAIL\x10\x03*c\n" +
	"\x0fMessageUnitType\x12!\n" +
	"\x1dMESSAGE_UNIT_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01\x12\b\n" +
	"\x04CALL\x10\x02\x12\n" +
	"\n" +
	"\x06ANSWER\x10\x03\x12\r\n" +
	"\tESTABLISH\x10\x04B)\n" +
	"\x1dcom.github.xiawusharve.webrtcH\x03Z\x06datas/b\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_message_proto_goTypes = []any{
	(MessageType)(0),     // 0: message.MessageType
	(AckStatus)(0),       // 1: message.AckStatus
	(MessageUnitType)(0), // 2: message.MessageUnitType
	(*Message)(nil),      // 3: message.Message
	(*Sdp)(nil),          // 4: message.Sdp
	(*Connect)(nil),      // 5: message.Connect
	(*Ack)(nil),          // 6: message.Ack
	(*Candidate)(nil),    // 7: message.Candidate
	(*Chat)(nil),         // 8: message.Chat
	(*MessageUnit)(nil),  // 9: message.MessageUnit
}
var file_message_proto_depIdxs = []int32{
	0, // 0: message.Message.type:type_name -> message.MessageType
	6, // 1: message.Message.ack:type_name -> message.Ack
	7, // 2: message.Message.candidate:type_name -> message.Candidate
	8, // 3: message.Message.chat:type_name -> message.Chat
	4, // 4: message.Message.call:type_name -> message.Sdp
	4, // 5: message.Message.answer:type_name -> message.Sdp
	1, // 6: message.Ack.status:type_name -> message.AckStatus
	9, // 7: message.Chat.message_chain:type_name -> message.MessageUnit
	2, // 8: message.MessageUnit.type:type_name -> message.MessageUnitType
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_message_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_Ack)(nil),
		(*Message_Candidate)(nil),
		(*Message_Chat)(nil),
		(*Message_Call)(nil),
		(*Message_Answer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
